### ISSUE TITLE
handle comments

### ISSUE THREAD

**Issue by bremner** [LuKuangChen/stacker-2023#7]
The motivation is the same as #6, but I don't know if this is harder or easier.

Currently I am getting "The variable `;;` is not defined." from e.g.

https://www.cs.unb.ca/~bremner/teaching/cs4613/stacker/?program=;;+f+is+the+same+as+before%0A%28deffun+%28g+z%29%0A++%28f+%28%2B+z+4%29%29%29%0A%28g+5%29%0A

**Comment by LuKuangChen** [comment]
[45fa38c](https://github.com/LuKuangChen/stacker-2023/commit/45fa38c91eb622ee2c1e611d85b3d96e0e3ca644) fixes this problem. I added support for line comment, for example,

https://lukuangchen.github.io/stacker-2023/?syntax=Lispy&randomSeed=2023&nNext=0&program=%3B%3B+f+is+the+same+as+before%0A%28deffun+%28g+z%29%0A++%28f+%28%2B+z+4%29%29%29%0A%28g+5%29&readOnlyMode=

 and experimental* support for S-expression comment (`#;`), for example,

https://lukuangchen.github.io/stacker-2023/?syntax=Lispy&randomSeed=2023&nNext=0&program=%23%3B%28f+is+the+same+as+before%29%0A%28deffun+%28g+z%29%0A++%28f+%28%2B+z+4%29%29%29%0A%28g+5%29&readOnlyMode=

*: This support is experimental because the editor doesn't highlight commented parts properly.
